# This is a basic workflow to help you get started with Actions

name: Auto Syncing CI

on:
  push:
    branches: [master]



jobs:
  
  build:
   
    runs-on: ubuntu-latest

    
    steps:
    
    - uses: actions/checkout@v2
    - name: Git-version
      run: git version
    - name: Git-remote-add
      run: git remote add origin https://github.com/shrikant9867/SAIL-BPM.git
    - name: Git-fetch-all
      run: git fetch --all
    - name: Git Another Remote
      run: git remote add upstream  https://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@github.com/avinashnarvekar/SAIL-Delivey-Note.git
    - name: Git-push
      run: git push upstream master
