  
# This is a basic workflow to help you get started with Actions

name: Auto Deployment of Frappe CLoud Repo Codebase Changes on Running Container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

# Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow copy from one repo to another repo
jobs:
  # This workflow contains a single job called "build"
  build:
     name: Deployment Started on Server
     runs-on: ubuntu-latest
     steps:
     - name: executing remote ssh commands using secrets
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.UAT_HOST }}
         username: ${{ secrets.UAT_USERNAME }}
         key: ${{ secrets.UAT_51_SERVER_PEM }}
         port: 1993
         script: |
           cd /home/dairy/webapps/version-13-beta/frappe-bench/apps/sail_bpm;
           export GIT_SSL_NO_VERIFY=1;
           git pull --rebase upstream $(git rev-parse --abbrev-ref HEAD);
           cd ../..;
           source ../bin/activate;
           bench --site test.sail_bpm migrate &> /dev/null  && bench --site test.sail_bpm build  &> /dev/null && bench --site test.sail_bpm clear-cache;
           cd ./apps/sail_bpm;
           git push Sail-bpm-upstream master;
